services:
  db:
    image: postgres:17
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment: 
      POSTGRES_DB: mlb_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: syncopate
    ports:
    - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres_data: